### ISSUE TITLE
Error when downoading requirements

### ISSUE THREAD

**Issue by antoineok** [ArronDavies/Pika-Chewniverse-2.0#3]
i got this error when install the requirements, here are the errors:
  Running command git checkout -q pyraknetmod
  error: pathspec 'pyraknetmod' did not match any file(s) known to git.
ERROR: Command errored out with exit status 1: git checkout -q pyraknetmod Check the logs for full command output.
I got this after using the following command:
pip3.7 install -r requirements.txt

**Comment by ArronDavies** [comment]
Hi antoineok,
I have just pushed an update which fixes this issue. If you experience any other issues please let me know, I will be leaving this issue open for the next day or two.

**Comment by antoineok** [comment]
I don't have the maps folder, where it is stock (in the client game file)?

**Comment by antoineok** [comment]
ah, and sorry if the text is not really good, i'm not english

**Comment by ArronDavies** [comment]
Hi antoineok,
Inside: `<YourGameLocation>\res\` is the maps folder
copy that folder into the `clientfiles` folder on the server.

Inside the `clientfiles` folder should then look like this:
![image](https://user-images.githubusercontent.com/18177713/83998943-9bd78e00-a959-11ea-8698-d484b2a1f9e9.png)

**Comment by antoineok** [comment]
i don't have the maps folder inside, how did i get it?

**Comment by antoineok** [comment]
wait, i will download another client, a unpacked one, maybe it wil work better

**Comment by ArronDavies** [comment]
Sorry I forgot to mention that, an unpacked client is needed for the map files.

**Comment by antoineok** [comment]
how did i add an user?

**Comment by Jettford** [comment]
There is no easy way to add a user at the moment I may add a API later to allow for easy account creation and moderation but the current build has a default account with the login Player and 123

**Comment by Jettford** [comment]
I have put some work into a easy to use API so that accounts and things can be easier
